hello 

ROCK PAPER SCISSORS 

USER INPUTS ROCK PAPER OR SCISSORS

COMPUTER CHOOSES ROCK PAPER OR SCISSORS

A WINNER IS DECIDED FOR THE ROUND

THE WINNER GETS 1 WIN COUNTED

GO BACK TO START UNTIL SOMEONE WINS 5 TIMES 